kind: CronJob
apiVersion: batch/v1
metadata:
  name: cron-job-print
  namespace: nginx

spec:
  schedule: "* * * * *" 
  jobTemplate:
    spec:
      template:
        metadata:
          name: cron-job-pod
          labels:
            app: cron-job-label
        spec:
          containers:
          - name: cron-job-container
            image: busybox:latest
            command:
            - /bin/sh
            - -c
            - date; echo Printing cron-job scheduled for every day every minute
          restartPolicy: OnFailure
