kind: Job
apiVersion: batch/v1
metadata:
  name: demo-job
  namespace: nginx

spec:
  completions: 1
  parallelism: 1
  template:
    metadata:
      name: demo-job-pod
      labels:
        app: demo-job-label
    spec:
      containers:
      - name: job-container
        image: busybox:latest
        command: ["sh", "-c", "echo Demo-job created and executed!! && sleep 10"]
      restartPolicy: Never
