kind: Service
apiVersion: v1
metadata:
  name: apache-service
  namespace: apache-ns
spec:
  selector:
      app: apache-lb
  ports:
    - protocol: TCP
      port: 80 #exposed port in the cluster
      targetPort: 80 # container port
  type: ClusterIP

