kind: VerticalPodAutoscaler
apiVersion: autoscaling.k8s.io/v1
metadata:
  name: apache-vpa
  namespace: apache-ns
spec:
  targetRef:
    name: apache-deployment
    apiVersion: app/v1
    kind: deployment
  updatePolicy:
    updateMode: "Auto"

